---
name: Build & Test
description: Build the final container image and run tests on it

inputs:
  registry:
    description: Target registry to push the final image.
    default: "localhost:5000"
  namespace:
    description: Namespace of the container image.
    default: ansible
  final_image:
    description: Name of the final image.
    default: community-ansible-dev-tools-container

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare
      shell: bash
      run: |
        platform=${{ matrix.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.FINAL_IMAGE }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # network=host driver-opt needed to push to local registry
        driver-opts: network=host

    - name: Install ansible-builder
      shell: bash
      id: ansible-builder-install
      run: |
        python3 -m pip install ansible-builder

    - name: Verify ansible-builder installed
      shell: bash
      id: ansible-builder-verify
      run: |
        ansible-builder --version

    - name: Build base image for ${{ matrix.platform }}
      uses: docker/build-push-action@v5
      id: build_base
      with:
        context: base
        provenance: false
        file: base/Containerfile
        platforms: ${{ matrix.platform }}
        push: true
        tags: localhost:5000/${{ inputs.final_image }}-base:latest
        cache-from: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
        cache-to: type=gha,scope=build-${{ env.PLATFORM_PAIR }}

    - name: Show available images & base image manifest
      shell: bash
      run: |
        curl -X GET http://localhost:5000/v2/${{ inputs.final_image }}-base/tags/list
        docker manifest inspect localhost:5000/${{ inputs.final_image }}-base --insecure -v

    - name: Create a build context and ContainerFile for the final image
      shell: bash
      run: |
        ansible-builder create -f ${{ github.workspace }}/execution-environment.yml --output-filename Containerfile -v3

    - name: Build and push final image by digest for ${{ matrix.platform }}
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}/context
        provenance: false
        file: ${{ github.workspace }}/context/Containerfile
        build-contexts: |
          ${{ inputs.final_image }}-base=docker-image://localhost:5000/${{ inputs.final_image }}-base:latest
        platforms: ${{ matrix.platform }}
        outputs: type=image,name=${{ inputs.registry }}/${{ inputs.namespace }}/${{ inputs.final_image }},push-by-digest=true,name-canonical=true,push=true
        cache-from: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
        cache-to: type=gha,scope=build-${{ env.PLATFORM_PAIR }}

    - name: Export digest
      shell: bash
      run: |
        rm -rf /tmp/digests
        mkdir -p /tmp/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "/tmp/digests/${digest#sha256:}"

    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ env.PLATFORM_PAIR }}
        path: /tmp/digests/*
        if-no-files-found: error
        retention-days: 1
