---
version: 3

images:
  base_image:
    name: community-ansible-dev-tools-container-base:latest

dependencies:
  ansible_runner:
    package_pip: ansible-runner
  
  ansible_core:
    package_pip: ansible-core

  galaxy: requirements.yml

options:
  container_init:
    entrypoint: '["/usr/bin/zsh"]'
  package_manager_path: /usr/bin/microdnf
  user: podman
  workdir: /home/podman

additional_build_steps:
  prepend_base:
    - LABEL org.opencontainers.image.source https://github.com/ansible-community/community-ansible-dev-tools-container
    - LABEL org.opencontainers.image.authors "Ansible DevTools"
    - LABEL org.opencontainers.image.vendor "Red Hat"
    - LABEL org.opencontainers.image.licenses "GPL-3.0"
    - LABEL org.opencontainers.image.description "A community container image for Ansible Devtools."
  append_final:
    # Related to https://github.com/ohmyzsh/ohmyzsh/issues/6835
    # This is done in the original base image, but, somewhere in
    # between the builder base and the builder final image this gets changed to 775
    - RUN chmod 755 /home/podman/.oh-my-zsh && chmod 755 /home/podman/.oh-my-zsh/cache
    # add some helpful CLI commands to check we do not remove them inadvertently and output some helpful version information at build time.
    - RUN set -ex
        && ansible --version
        && ansible-lint --version
        && ansible-runner --version
        && molecule --version
        && molecule drivers
        && podman --version
        && python3 --version
        && git --version
        && ansible-galaxy role list
        && ansible-galaxy collection list
        && rpm -qa
        && uname -a
