---
version: 3

images:
  base_image:
    name: quay.io/fedora/fedora-minimal:39

dependencies:
  ansible_runner:
    package_pip: ansible-runner
  
  ansible_core:
    package_pip: ansible-core

  galaxy: requirements.yml

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_base:
    - RUN $PKGMGR -y install python3-devel
  append_final:
    - LABEL org.opencontainers.image.source https://github.com/ansible-community/community-ansible-dev-tools-container/blob/main/base/ContainerFile
    - LABEL org.opencontainers.image.authors "Ansible DevTools"
    - LABEL org.opencontainers.image.vendor "Red Hat"
    - LABEL org.opencontainers.image.licenses "GPL-3.0"
    - LABEL org.opencontainers.image.description "A base execution environment for Ansible Devtools Container."
