---
name: ci

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ${{ matrix.builder }}
    permissions: write-all
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    strategy:
      fail-fast: false
      matrix:
        include:
          - builder: devtools-multiarch-builder
            platform: linux/amd64
          - builder: devtools-arm64-runner
            platform: linux/arm64

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the container image for ${{ matrix.platform }} and test it
        uses: ansible/community-ansible-dev-tools-container/.github/actions/build-test@main
